#!/usr/bin/env bash
#
# list IP addresses connected to this computer

NETSTAT=$(sudo netstat -nputw | tail -n +3)
count=$(echo "$NETSTAT" | wc -l)
echo "$count connections..."
echo ""

while read -r line; do
  PROC=$(echo "$line" | awk '{print $7}' | sed 's:\(.*\)/\(.*\):\2 (\1):')
  IP=$(echo "$line" | awk '{print $5}' | sed 's/\(.*\):.*/\1/')

  echo "$PROC = $IP"

  RDNS=$(dig -x $IP +short)
  if [ ! "$RDNS" ]; then RDNS="noRDNS"; fi
  ORG=$(whois $IP | grep -i orgname | sed 's/.*: *\(.*\)/\1/')
  if [ ! "$ORG" ]; then ORG="noORGNAME"; fi

  echo "$RDNS | $ORG"
  echo ""
done <<< "$NETSTAT"

