#!/usr/bin/env bash

ips=()
num=0
echo ""

for i in $(seq 0 255); do
    echo -ne "Current: $1$i - Replies: $(printf %-3d $num)\r"
    reply=$(ping -b -c 1 -W 1 "$1$i" 2>/dev/null)
    packets=$(echo "$reply" | grep received | sed "s:.*, \(.*\) received.*:\1:g")
    if [ "$packets" = "1" ]; then
        ((num+=1))
        ips+=("$1$i")
    fi
    echo -ne "Current: $1$i - Replies: $(printf %-3d $num)\r"
done

echo -ne "\033[2K"

if [ "$ips" ]; then
    for ip in "${ips[@]}"; do
        echo "$ip"
    done
else
    echo "No replies"
fi

echo ""
