#!/usr/bin/env python

import sys

from emailer import Emailer

def main(msg,recip):
  
  e = Emailer('notify@jahschwa.com','xS%9ahdKvqL+p*dY','jahschwa.com')
  e.send(msg,recip)

if __name__ == '__main__':
  main(sys.argv[1],sys.argv[2])
