#!/usr/bin/env bash
#
# Usage:
#
#   xmpp host [hostname]

if [ "$2" ]; then
  HOST="$2"
else
  HOST="$1"
fi

echo ""
echo "<stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' to='$2' version='1.0'>" | nc "$1" 5222
echo ""
echo ""
